# Generated by Django 5.0.6 on 2024-09-01 01:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Ishchi ',
                'verbose_name_plural': 'Ishchilar ',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_o', models.CharField(max_length=60)),
                ('telefon_raqam', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField(blank=True, null=True)),
                ('zayafka_vaqti', models.DateTimeField(auto_now_add=True)),
                ('tekshirilgan_vaqti', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('KELADI', 'KELADI'), ('ULANILMADI', 'ULANILMADI'), ('QOLDIRILDI', 'QOLDIRILDI'), ('KEMIDI', 'KEMIDI')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ishchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.worker')),
            ],
            options={
                'verbose_name': 'Mijoz ',
                'verbose_name_plural': 'Mijozlar ',
            },
        ),
    ]
