# Generated by Django 5.0.6 on 2024-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Потенциальный', 'Потенциальный'), ('Просто интересовался', 'Просто интересовался'), ('Не поднял телефон', 'Не поднял телефон')], max_length=20, null=True),
        ),
    ]
